<?php

namespace Realodix\PhpCsFixerConfig\RuleSet;

final class PHPUnit extends AbstractRuleSet implements RuleSetExplicitInterface
{
    protected $name = 'PHPUnit Coding Standards';

    /**
     * sebastianbergmann/phpunit
     * https://github.com/sebastianbergmann/phpunit/blob/master/.php-cs-fixer.dist.php
     *
     * Diff
     * - [D] global_namespace_import.import_classes Same as the default value
     * - [D] header_comment                         Must be set manually
     * - [M] class_attributes_separation
     * - [M] list_syntax
     * - [M] ordered_interfaces
     * - [M] trailing_comma_in_multiline
     */
    public function myRules(): array
    {
        $rules = [
            '@PSR12'                       => true,
            'braces'                       => true,
            'blank_line_after_opening_tag' => false,
            'new_with_braces'              => false,
            'ordered_class_elements'       => [
                'order' => [
                    'use_trait', 'constant_public', 'constant_protected', 'constant_private',
                    'property_public_static', 'property_protected_static', 'property_private_static',
                    'property_public', 'property_protected', 'property_private', 'method_public_static',
                    'construct', 'destruct', 'magic', 'phpunit', 'method_public', 'method_protected',
                    'method_private', 'method_protected_static', 'method_private_static',
                ],
            ],
            'ordered_imports config'             => true,
            'single_blank_line_before_namespace' => false,
            'single_class_element_per_statement' => true,
            'visibility_required'                => true,
            //
            'array_syntax'                    => true,
            'align_multiline_comment'         => true,
            'array_indentation'               => true,
            'array_push'                      => true,
            'backtick_to_shell_exec'          => true,
            'cast_spaces'                     => true,
            'class_attributes_separation'     => true,
            'clean_namespace'                 => true,
            'combine_consecutive_issets'      => true,
            'combine_consecutive_unsets'      => true,
            'combine_nested_dirname'          => true,
            'concat_space'                    => ['spacing' => 'one'],
            'declare_strict_types'            => true,
            'dir_constant'                    => true,
            'echo_tag_syntax'                 => true,
            'ereg_to_preg'                    => true,
            'explicit_indirect_variable'      => true,
            'explicit_string_variable'        => true,
            'fopen_flag_order'                => true,
            'fully_qualified_strict_types'    => true,
            'function_to_constant'            => true,
            'function_typehint_space'         => true,
            'global_namespace_import'         => ['import_constants' => true, 'import_functions' => true],
            'heredoc_to_nowdoc'               => true,
            'implode_call'                    => true,
            'include'                         => true,
            'increment_style'                 => ['style' => 'post'],
            'is_null'                         => true,
            'lambda_not_used_import'          => true,
            'list_syntax'                     => true,
            'logical_operators'               => true,
            'magic_constant_casing'           => true,
            'magic_method_casing'             => true,
            'modernize_types_casting'         => true,
            'native_constant_invocation'      => false,
            'native_function_casing'          => false,
            'native_function_invocation'      => false,
            'no_alias_functions'              => true,
            'no_alternative_syntax'           => true,
            'no_binary_string'                => true,
            'no_blank_lines_after_phpdoc'     => true,
            'no_blank_lines_before_namespace' => true,
            'no_empty_comment'                => true,
            'no_empty_phpdoc'                 => true,
            'no_empty_statement'              => true,
            'no_extra_blank_lines'            => true,
            'no_homoglyph_names'              => true,
            'no_mixed_echo_print'             => ['use' => 'print'],
            'no_php4_constructor'             => true,
            'no_short_bool_cast'              => true,
            'no_spaces_around_offset'         => true,
            'no_superfluous_elseif'           => true,
            'no_superfluous_phpdoc_tags'      => ['allow_mixed' => true],
            'no_trailing_comma_in_list_call'  => true,
            'no_unneeded_control_parentheses' => true,
            'no_unneeded_curly_braces'        => true,
            'no_unneeded_final_method'        => true,
            'no_unset_cast'                   => true,
            'no_unset_on_property'            => true,
            'no_unused_imports'               => true,
            'no_useless_else'                 => true,
            'no_useless_return'               => true,
            'no_useless_sprintf'              => true,
            'non_printable_character'         => true,
            'normalize_index_brace'           => true,
            'operator_linebreak'              => ['only_booleans' => true, 'position' => 'end'],
            'ordered_imports'                 => ['imports_order' => ['const', 'class', 'function']],
            'ordered_interfaces'              => true,
            'ordered_traits'                  => true,
            'phpdoc_align'                    => true,
            'phpdoc_annotation_without_dot'   => true,
            'phpdoc_indent'                   => true,
            'phpdoc_inline_tag_normalizer'    => true,
            'phpdoc_no_access'                => true,
            'phpdoc_no_alias_tag'             => true,
            'phpdoc_no_empty_return'          => true,
            'phpdoc_no_package'               => true,
            'phpdoc_no_useless_inheritdoc'    => true,
            'phpdoc_order_by_value'           => ['annotations' => ['covers', 'dataProvider', 'throws', 'uses']],
            'phpdoc_order'                    => true,
            'phpdoc_return_self_reference'    => true,
            'phpdoc_scalar'                   => true,
            'phpdoc_separation'               => true,
            'phpdoc_single_line_var_spacing'  => true,
            'phpdoc_summary'                  => true,
            'phpdoc_tag_casing'               => true,
            'phpdoc_tag_type'                 => true,
            'phpdoc_to_comment'               => true,
            'phpdoc_trim'                     => true,
            'phpdoc_types_order'              => true,
            'phpdoc_types'                    => ['groups' => ['simple', 'meta']],
            'phpdoc_var_without_name'         => true,
            'pow_to_exponentiation'           => true,
            'protected_to_private'            => true,
            'return_assignment'               => true,
            'self_accessor'                   => true,
            'self_static_accessor'            => true,
            'semicolon_after_instruction'     => true,
            'set_type_to_cast'                => true,
            'simplified_null_return'          => false,
            'single_quote'                    => true,
            'single_space_after_construct'    => true,
            'space_after_semicolon'           => true,
            'standardize_increment'           => true,
            'standardize_not_equals'          => true,
            'static_lambda'                   => true,
            'strict_param'                    => true,
            'string_line_ending'              => true,
            'switch_continue_to_break'        => true,
            'ternary_to_elvis_operator'       => true,
            'ternary_to_null_coalescing'      => true,
            'trailing_comma_in_multiline'     => true,
            'trim_array_spaces'               => true,
            'unary_operator_spaces'           => true,
            'void_return'                     => true,
            'whitespace_after_comma_in_array' => true,

            'multiline_comment_opening_closing'             => true,
            'multiline_whitespace_before_semicolons'        => true,
            'native_function_type_declaration_casing'       => true,
            'no_alias_language_construct_call'              => true,
            'no_leading_namespace_whitespace'               => true,
            'no_multiline_whitespace_around_double_arrow'   => true,
            'no_null_property_initialization'               => true,
            'no_singleline_whitespace_before_semicolons'    => true,
            'no_trailing_comma_in_singleline_array'         => true,
            'no_trailing_whitespace_in_string'              => true,
            'no_unreachable_default_argument_value'         => true,
            'no_whitespace_before_comma_in_array'           => true,
            'object_operator_without_whitespace'            => true,
            'php_unit_set_up_tear_down_visibility'          => true,
            'php_unit_test_case_static_method_calls'        => ['call_type' => 'this'],
            'phpdoc_add_missing_param_annotation'           => false,
            'phpdoc_trim_consecutive_blank_line_separation' => true,
            'phpdoc_var_annotation_correct_order'           => true,
            'simple_to_complex_string_variable'             => true,
            'binary_operator_spaces'                        => [
                'operators' => [
                    '='  => 'align_single_space_minimal',
                    '=>' => 'align_single_space_minimal',
                    '|'  => null,
                ],
            ],
            'blank_line_before_statement' => [
                'statements' => [
                    'break', 'continue', 'declare', 'default', 'do', 'exit', 'for',
                    'foreach', 'goto', 'if', 'include', 'include_once', 'require',
                    'require_once', 'return', 'switch', 'throw', 'try', 'while', 'yield',
                ],
            ],
        ];

        return $rules;
    }
}
