name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.1','7.2','7.3','7.4','8.0']
        include:
          - php-version: '8.1'
            flags: "--ignore-platform-req=php"

    name: PHP ${{ matrix.php-version }} - Integrate PHP CS Fixer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      # https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
              composer -V
              composer install --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}

      - name: Run friendsofphp/php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
